#ifndef GUIDANCE_PROTOCOL_GENERATED_H
#define GUIDANCE_PROTOCOL_GENERATED_H

/* Auto-generated from protocol/guidance_protocol.yaml. */

#define GUIDANCE_PROTOCOL_FRAME_HEADER_0 0xA5U
#define GUIDANCE_PROTOCOL_FRAME_HEADER_1 0x5AU

#define ESP32_LINK_MESSAGE_TYPE_GUIDANCE_TELEMETRY 0x01U
#define ESP32_LINK_MESSAGE_TYPE_IMU_ACCEL 0x04U
#define ESP32_LINK_MESSAGE_TYPE_IMU_MOTION 0x05U
#define ESP32_LINK_MESSAGE_TYPE_DART_LAUNCH_SAMPLE 0x06U

#endif
