from __future__ import annotations

from pathlib import Path

from guidance_host_common import YamlLiteParser


OPENMV_DETECTOR_PARAM_FIELDS = (
    ("openmv_threshold_l_min", "threshold_l_min"),
    ("openmv_threshold_l_max", "threshold_l_max"),
    ("openmv_threshold_a_min", "threshold_a_min"),
    ("openmv_threshold_a_max", "threshold_a_max"),
    ("openmv_threshold_b_min", "threshold_b_min"),
    ("openmv_threshold_b_max", "threshold_b_max"),
    ("openmv_min_area", "min_area"),
    ("openmv_max_area", "max_area"),
    ("openmv_roundness_min_x1000", "roundness_min_x1000"),
    ("openmv_merge_margin", "merge_margin"),
    ("openmv_track_window_radius_px", "track_window_radius_px"),
    ("openmv_max_missed_frames", "max_missed_frames"),
    ("openmv_ring_detection_enabled", "ring_detection_enabled"),
    ("openmv_ring_min_roundness_x1000", "ring_min_roundness_x1000"),
    ("openmv_ring_min_aspect_x100", "ring_min_aspect_x100"),
    ("openmv_ring_min_fill_x100", "ring_min_fill_x100"),
    ("openmv_ring_max_fill_x100", "ring_max_fill_x100"),
    ("openmv_ring_min_center_white_x100", "ring_min_center_white_x100"),
    ("openmv_ring_center_sample_ratio_x100", "ring_center_sample_ratio_x100"),
    ("openmv_ring_center_min_brightness", "ring_center_min_brightness"),
    ("openmv_ring_center_max_channel_delta", "ring_center_max_channel_delta"),
    ("openmv_ring_min_outer_diameter_px", "ring_min_outer_diameter_px"),
    ("openmv_threshold_small_l_min", "threshold_small_l_min"),
    ("openmv_threshold_small_l_max", "threshold_small_l_max"),
    ("openmv_threshold_small_a_min", "threshold_small_a_min"),
    ("openmv_threshold_small_a_max", "threshold_small_a_max"),
    ("openmv_threshold_small_b_min", "threshold_small_b_min"),
    ("openmv_threshold_small_b_max", "threshold_small_b_max"),
    ("openmv_threshold_small_area_max", "threshold_small_area_max"),
)


def detector_param_dict_from_config(config: dict) -> dict[str, int]:
    green_light = config.get("green_light")
    if not isinstance(green_light, dict):
        raise ValueError("guidance params missing required section: green_light")

    params: dict[str, int] = {}
    missing_keys: list[str] = []
    for yaml_key, detector_key in OPENMV_DETECTOR_PARAM_FIELDS:
        if yaml_key not in green_light:
            missing_keys.append("green_light." + yaml_key)
            continue
        params[detector_key] = int(green_light[yaml_key])

    if missing_keys:
        raise ValueError("guidance params missing required OpenMV keys: " + ", ".join(missing_keys))
    return params


def load_openmv_detector_param_dict(config_path: str | Path) -> dict[str, int]:
    config = YamlLiteParser().parse_file(str(config_path))
    return detector_param_dict_from_config(config)


def build_openmv_generated_params_text(config_path: str | Path) -> str:
    config_path = Path(config_path)
    params = load_openmv_detector_param_dict(config_path)
    lines = [
        "# Auto-generated by OpenMV_guidance/tools/openmv_cli.py.",
        "# Source: " + config_path.as_posix(),
        "",
        "OPENMV_DETECTOR_PARAMS = {",
    ]
    for _, detector_key in OPENMV_DETECTOR_PARAM_FIELDS:
        lines.append(f"    {detector_key!r}: {params[detector_key]},")
    lines.extend(["}", ""])
    return "\n".join(lines)
