[platformio]
default_envs = genericSTM32G431CB
src_dir = .

[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = stm32cube

upload_protocol = custom
upload_command = $PROJECT_PACKAGES_DIR/tool-openocd/bin/openocd -f interface/stlink.cfg -f target/stm32g4x.cfg -c "adapter speed 100" -c "program $BUILD_DIR/${PROGNAME}.elf verify reset exit"
debug_tool = stlink

monitor_speed = 115200
monitor_port = /dev/ttyUSB0

board_build.ldscript = STM32G431XX_FLASH.ld
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.custom_system_setup = yes

extra_scripts = pre:pio_extra.py, pre:pio_pre_protocol.py, post:pio_post.py

build_src_filter =
  +<Core/Src/main.c>
  +<Core/Src/gpio.c>
  +<Core/Src/dma.c>
  +<Core/Src/spi.c>
  +<Core/Src/tim.c>
  +<Core/Src/usart.c>
  +<Core/Src/stm32g4xx_it.c>
  +<Core/Src/stm32g4xx_hal_msp.c>
  +<Core/Src/sysmem.c>
  +<Core/Src/syscalls.c>
  +<Core/Src/system_stm32g4xx.c>
  +<APP/Src/imu.c>
  +<APP/Src/task.c>
  +<APP/Src/target_smoother.c>
  +<APP/Src/green_light_task.c>
  +<APP/Src/pixel_delta_pid_action.c>
  +<APP/Src/imu_velocity_recovery_action.c>
  +<APP/Src/timed_turn_pulse_action.c>
  +<APP/Src/guidance_planner.c>
  +<APP/Src/control_mixer.c>
  +<APP/Src/guidance_controller.c>
  +<Drv/Src/bmi088.c>
  +<Drv/Src/esp32_link.c>
  +<Drv/Src/servo.c>
  +<Drv/Src/interface.c>
  +<Lib/Src/mahony.c>
  +<Lib/Src/pid.c>
  +<startup_stm32g431xx.s>
  -<build/>
  -<cmake/>

build_flags =
  -ICore/Inc
  -IAPP/Inc
  -IDrv/Inc
  -ILib/Inc
  -IDrivers/CMSIS/DSP/Include
  -DUSE_HAL_DRIVER
  -DSTM32G431xx
  -DARM_MATH_CM4
  -DARM_MATH_DSP
  -LDrivers/CMSIS/DSP/Lib/GCC
  -larm_cortexM4lf_math

build_unflags =
  -Os

build_type = debug
