[platformio]
default_envs = openmv_cam
build_dir = .pio/build

[env:openmv_cam]
platform = native
extra_scripts = post:tools/upload_openmv_sources.py

[openmv]
port = /dev/ttyACM0
script = src/main.py
